### ISSUE TITLE
Does not handle unicode email addresses?

### ISSUE THREAD

**Issue by jmduke** [zsiciarz/django-envelope#46]
First off -- thanks for the library!  It's been a huge help for our team and we appreciate the work.

It looks like we've run into a snag with the contact form's handling of unicode email addresses (the email address spec handles latin1 characters as long as they're utf-8): posting the following payload will result in an exception:

```
{
            'sender': ['á'],
            'message': ['Hello world!'],
            'email': 'foo@nobody.com',
}
```

And the exception:

`'ascii' codec can't encode character u'\xe1' in position 16: ordinal not in range(128)`

Please let me know if you need any more information from our end!  Thanks again and have a great Tuesday.

**Comment by SebCorbin** [comment]
Cleaning up old issues... Do you mind reopening this if you still have this error? Don't forget to add your python, django and package version.
