### ISSUE TITLE
TypeError: 'bool' object is not callable 

### ISSUE THREAD

**Issue by marquicus** [zsiciarz/django-envelope#50]
File "/home/marp/.virtualenvs/smsgateway/lib/python3.6/site-packages/envelope/views.py", line 76, in get_initial                                     
    if user.is_authenticated():                                                                                                                        
TypeError: 'bool' object is not callable 

Django 2.0.4

**Comment by davePlug** [comment]
Django 2.0.6 is showing the same issue.
I believe it's because is_authenticated is not a function anymore

**Comment by SebCorbin** [comment]
This has been fixed by #54
