### ISSUE TITLE
Compatibility with Django 3.0

### ISSUE THREAD

**Issue by richardbarran** [zsiciarz/django-envelope#55]
Hi to all,
I've patched this package to work with Django 3.0.
I've tried to contact the package author in the past - but without success - in order to review a past PR (Django 2.2 compatibility).
While I'm waiting for him/her to update this repo, I have forked the repository, brought it up to date, and uploaded it to PyPI as [django-envelope-updated](https://pypi.org/project/django-envelope-updated/).
My fork is at https://github.com/richardbarran/django-envelope
I hope that this may be of use to other users of this great little package who want to continue using it with the latest versions of Django.

**Comment by SebCorbin** [comment]
I'm closing this issue as your fork is now fully integrated in the project, thanks again!

**Comment by richardbarran** [comment]
Hi - thank you for taking over this project.
