### ISSUE TITLE
Travis CI - end of a era

### ISSUE THREAD

**Issue by richardbarran** [zsiciarz/django-envelope#64]
This project currently uses Travis CI - however the "free plans" on Travis are being phased out.
Lots of other open source projects are migrating to Github Actions. If I submitted a PR for switching to Github Actions would it be something that would of interest?

**Comment by zsiciarz** [comment]
Hey @richardbarran , a PR would be most welcome! I've barely started converting some of my other projects to GHA so any help is appreciated.
